### ISSUE TITLE
Add Changelog MD

### ISSUE THREAD

**Issue by investor55** [UBC-MDS/522_group_36#60]
- Create File

Please comment down your changes in detail.

**Comment by YibinLong** [comment]
Check the changelog branch for the initialized changelog #70

**Comment by lixuanlinjam** [comment]
regarding this comment from [@adrianl726]: The figures are not rendered in the report html file. It is a bit hard to understand the findings solely from words and tables. I would suggest adding embed-resources: true to the yaml header in the .qmd file.

- change the report's output charts format from svg to png, better supporting html/github pages rendering.

**Comment by lixuanlinjam** [comment]
regarding this comment from @adrianl726: The organization of the folders is a bit messy and hard to navigate. For instance, the results/ directory only contains one empty file called placeholder when I am expecting to find actual results from the project in this directory. I would suggest moving the figure and table outputs to this directory as they are parts of the results.

- deleted results directory, just keep the charts folder since outputs are all charts, to make the organization cleaner

**Comment by lixuanlinjam** [comment]
regarding improving the README.md instructions:

- corrected some typo
- adjusted some commands to make their style consistent
- adjusted to make the instruction command lines in the correct order
- added Makefile instructions

**Comment by investor55** [comment]
Logging configuration:

* [`scripts/run_validation.py`](diffhunk://#diff-4a7a926a43d976bc2fc0cfb78839df350e02f9e6191061859727d48c01101f66L24-R46): Added logging configuration to log correlation errors and created a `logs` directory with a `.gitkeep` file if it does not exist.

Dependency removal:

* [`scripts/run_validation.py`](diffhunk://#diff-4a7a926a43d976bc2fc0cfb78839df350e02f9e6191061859727d48c01101f66L6-R6): Removed the import of `click` and the `@click.command()` decorator. [[1]](diffhunk://#diff-4a7a926a43d976bc2fc0cfb78839df350e02f9e6191061859727d48c01101f66L6-R6) [[2]](diffhunk://#diff-4a7a926a43d976bc2fc0cfb78839df350e02f9e6191061859727d48c01101f66L24-R46)

Codebase simplification:

* [`src/validation/correlation_validator.py`](diffhunk://#diff-7dd4331a43215edb9c3e8d0aab30fe13a2fc8c9e355cba3da4508bb3bb1b6404L5-L10): Removed redundant logging configuration since logging is now handled in the main script.…th .gitkeep. Remove click command because in the Makefile and Readme doesn't specify click.

**Comment by YibinLong** [comment]
"To help us easily, and correctly, assess this, please create a file called CHANGELOG.md that lives in the root of your repository. In this file describe any improvements you made to the project based on feedback, and point to evidence of these improvements. You can point us to evidence of addressing it by providing URLs to reference specific lines of code, commit messages, pull requests, etc. Be sure to add some narration when sharing these URLs so that it is easy for us to identify which changes to your work addressed which pieces of feedback." - https://pages.github.ubc.ca/mds-2024-25/DSCI_522_dsci-workflows_students/release/milestone4/milestone4.html

**Comment by YibinLong** [comment]
For each improvement:
- Describe the improvements you made based on feedback
- Point to evidence of these improvements (link URL to lines of code / commit messages / pull requests)
- Add narrations / explanations to the URLs that explain which **pieces of feedback** are addressed by the code
